[workspace]
members = [
    "alacritty",
    "alacritty_terminal",
    "alacritty_config",
    "alacritty_config_derive",
]
resolver = "2"

[profile.release]
lto = "thin"
debug = 1
incremental = false

[patch.crates-io]
copypasta = { git = "https://github.com/paretje/copypasta.git" }
